enum TYPE { ENUM = 1, LIST = 1, FLOAT = 2, INTE = 1, ASCII = 3, STRING = 3 };
int attrib_type[403] = {
//for dummy		Code 0;
	INTE,
//Acronym: AGENCY       Code: 1,
    ASCII,
//Acronym: BCNSHP               Code: 2,
	ENUM,
//Acronym: BUISHP               Code: 3,
	ENUM,
//Acronym: BOYSHP               Code: 4,
	ENUM,
//Acronym: BURDEP               Code: 5,
	FLOAT,
//Acronym: CALSGN               Code: 6,
	STRING,
//Acronym: CATAIR       Code: 7,
	LIST,
//Acronym: CATACH       Code: 8,
	LIST,
//Acronym: CATBRG       Code: 9,
	LIST,
//Acronym: CATBUA       Code: 10,
	ENUM,
//Acronym: CATCBL       Code: 11,
	ENUM,
//Acronym: CATCAN       Code: 12,
	ENUM,
//Acronym: CATCAM       Code: 13,
	ENUM,
//Acronym: CATCHP       Code: 14,
	ENUM,
//Acronym: CATCOA       Code: 15,
	ENUM,
//Acronym: CATCTR       Code: 16,
	ENUM,
//Acronym: CATCON       Code: 17,
	ENUM,
//Acronym: CATCOV       Code: 18,
	ENUM,
//Acronym: CATCRN       Code: 19,
	ENUM,
//Acronym: CATDAM       Code: 20,
	ENUM,
//Acronym: CATDIS       Code: 21,
	ENUM,
//Acronym: CATDOC       Code: 22,
	ENUM,
//Acronym: CATDPG       Code: 23,
	LIST,
//Acronym: CATFNC       Code: 24,
	ENUM,
//Acronym: CATFRY       Code: 25,
	ENUM,
//Acronym: CATFIF       Code: 26,
	ENUM,
//Acronym: CATFOG       Code: 27,
	ENUM,
//Acronym: CATFOR       Code: 28,
	ENUM,
//Acronym: CATGAT       Code: 29,
	ENUM,
//Acronym: CATHAF       Code: 30,
	LIST,
//Acronym: CATHLK       Code: 31,
	LIST,
//Acronym: CATICE       Code: 32,
	ENUM,
//Acronym: CATINB       Code: 33,
	ENUM,
//Acronym: CATLND       Code: 34,
	LIST,
//Acronym: CATLMK       Code: 35,
	LIST,
//Acronym: CATLAM               Code: 36,
	ENUM,
//Acronym: CATLIT       Code: 37,
	LIST,
//Acronym: CATMFA       Code: 38,
	ENUM,
//Acronym: CATMPA               Code: 39,
	LIST,
//Acronym: CATMOR               Code: 40,
	ENUM,
//Acronym: CATNAV               Code: 41,
	ENUM,
//Acronym: CATOBS               Code: 42,
	ENUM,
//Acronym: CATOFP               Code: 43,
	LIST,
//Acronym: CATOLB               Code: 44,
	ENUM,
//Acronym: CATPLE               Code: 45,
	ENUM,
//Acronym: CATPIL               Code: 46,
	ENUM,
//Acronym: CATPIP               Code: 47,
	LIST,
//Acronym: CATPRA               Code: 48,
	ENUM,
//Acronym: CATPYL               Code: 49,
	ENUM,
//Acronym: CATQUA               Code: 50,
	ENUM,
//Acronym: CATRAS               Code: 51,
	ENUM,
//Acronym: CATRTB               Code: 52,
	ENUM,
//Acronym: CATROS               Code: 53,
	LIST,
//Acronym: CATTRK               Code: 54,
	ENUM,
//Acronym: CATRSC               Code: 55,
	LIST,
//Acronym: CATREA               Code: 56,
	LIST,
//Acronym: CATROD               Code: 57,
	ENUM,
//Acronym: CATRUN       Code: 58,
	ENUM,
//Acronym: CATSEA               Code: 59,
	ENUM,
//Acronym: CATSLC               Code: 60,
	ENUM,
//Acronym: CATSIT               Code: 61,
	LIST,
//Acronym: CATSIW               Code: 62,
	LIST,
//Acronym: CATSIL               Code: 63,
	ENUM,
//Acronym: CATSLO               Code: 64,
	ENUM,
//Acronym: CATSCF               Code: 65,
	LIST,
//Acronym: CATSPM               Code: 66,
	LIST,
//Acronym: CATTSS               Code: 67,
	ENUM,
//Acronym: CATVEG               Code: 68,
	LIST,
//Acronym: CATWAT               Code: 69,
	ENUM,
//Acronym: CATWED               Code: 70,
	ENUM,
//Acronym: CATWRK               Code: 71,
	ENUM,
//Acronym: CATZOC               Code: 72,
	ENUM,
//Acronym: $SPACE               Code: 73,
	ENUM,
//Acronym: $CHARS               Code: 74,
	ASCII,
//Acronym: COLOUR               Code: 75,
	LIST,
//Acronym: COLPAT               Code: 76,
	LIST,
//Acronym: COMCHA               Code: 77,
	ASCII,
//Acronym: $CSIZE               Code: 78,
	FLOAT,
//Acronym: CPDATE               Code: 79,
	ASCII,
//Acronym: CSCALE               Code: 80,
	INTE,
//Acronym: CONDTN               Code: 81,
	ENUM,
//Acronym: CONRAD               Code: 82,
	ENUM,
//Acronym: CONVIS               Code: 83,
	ENUM,
//Acronym: CURVEL               Code: 84,
	FLOAT,
//Acronym: DATEND               Code: 85,
	ASCII,
//Acronym: DATSTA               Code: 86,
	ASCII,
//Acronym: DRVAL1               Code: 87,
	FLOAT,
//Acronym: DRVAL2               Code: 88,
	FLOAT,
//Acronym: DUNITS               Code: 89,
	ENUM,
//Acronym: ELEVAT               Code: 90,
	FLOAT,
//Acronym: ESTRNG       Code: 91,
	FLOAT,
//Acronym: EXCLIT               Code: 92,
	ENUM,
//Acronym: EXPSOU               Code: 93,
	ENUM,
//Acronym: FUNCTN       Code: 94,
	LIST,
//Acronym: HEIGHT               Code: 95,
	FLOAT,
//Acronym: HUNITS               Code: 96,
	ENUM,
//Acronym: HORACC               Code: 97,
	FLOAT,
//Acronym: HORCLR               Code: 98,
	FLOAT,
//Acronym: HORLEN               Code: 99,
	FLOAT,
//Acronym: HORWID               Code: 100,
	FLOAT,
//Acronym: ICEFAC               Code: 101,
	FLOAT,
//Acronym: INFORM               Code: 102,
	STRING,
//Acronym: JRSDTN               Code: 103,
	ENUM,
//Acronym: $JUSTH               Code: 104,
	ENUM,
//Acronym: $JUSTV               Code: 105,
	ENUM,
//Acronym: LIFCAP               Code: 106,
	FLOAT,
//Acronym: LITCHR               Code: 107,
	ENUM,
//Acronym: LITVIS       Code: 108,
	LIST,
//Acronym: MARSYS               Code: 109,
	ENUM,
//Acronym: MLTYLT               Code: 110,
	INTE,
	//Acronym: NATION              Code: 111,
	ASCII,
//Acronym: NATCON               Code: 112,
	LIST,
//Acronym: NATSUR               Code: 113,
	LIST,
//Acronym: NATQUA               Code: 114,
	LIST,
//Acronym: NMDATE               Code: 115,
	ASCII,
//Acronym: OBJNAM                       Code: 116,
	STRING,
//Acronym: ORIENT               Code: 117,
	FLOAT,
//Acronym: PEREND               Code: 118,
	ASCII,
//Acronym: PERSTA               Code: 119,
	ASCII,
//Acronym: PICREP               Code: 120,
	STRING,
//Acronym: PILDST               Code: 121,
	STRING,
//Acronym: PRCTRY               Code: 122,
	ASCII,
//Acronym: PRODCT               Code: 123,
	LIST,
//Acronym: PUBREF               Code: 124,
	STRING,
//Acronym: QUASOU               Code: 125,
	LIST,
//Acronym: RADWAL               Code: 126,
	ASCII,
//Acronym: RADIUS               Code: 127,
	FLOAT,
//Acronym: RECDAT               Code: 128,
	ASCII,
//Acronym: RECIND               Code: 129,
	ASCII,
//Acronym: RYRMGV               Code: 130,
	ASCII,
//Acronym: RESTRN       Code: 131,
	LIST,
//Acronym: SCAMAX               Code: 132,
	INTE,
//Acronym: SCAMIN               Code: 133,
	INTE,
//Acronym: SCVAL1               Code: 134,
	INTE,
//Acronym: SCVAL2                       Code: 135,
	INTE,
//Acronym: SECTR1               Code: 136,
	FLOAT,
//Acronym: SECTR2                       Code: 137,
	FLOAT,
//Acronym: SHIPAM                       Code: 138,
	ASCII,
//Acronym: SIGFRQ                       Code: 139,
	INTE,
//Acronym: SIGGEN                       Code: 140,
	ENUM,
//Acronym: SIGGRP                       Code: 141,
	ASCII,
//Acronym: SIGPER                       Code: 142,
	FLOAT,
//Acronym: SIGSEQ                       Code: 143,
	ASCII,
//Acronym: SOUACC               Code: 144,
	FLOAT,
//Acronym: SDISMX                       Code: 145,
	INTE,
//Acronym: SDISMN                       Code: 146,
	INTE,
//Acronym: SORDAT                       Code: 147,
	ASCII,
//Acronym: SORIND                       Code: 148,
	ASCII,
//Acronym: STATUS                       Code: 149,
	LIST,
//Acronym: SURATH                       Code: 150,
	STRING,
//Acronym: SUREND                       Code: 151,
	ASCII,
//Acronym: SURSTA                       Code: 152,
	ASCII,
//Acronym: SURTYP       Code: 153,
	LIST,
//Acronym: $SCALE       Code: 154,
	FLOAT,
//Acronym: $SCODE       Code: 155,
	ASCII,
//Acronym: TECSOU                       Code: 156,
	LIST,
//Acronym: $TXSTR       Code: 157,
	STRING,
//Acronym: TXTDSC       Code: 158,
	STRING,
//Acronym: TS_TSP               Code: 159,
	ASCII,
//Acronym: TS_TSV               Code: 160,
	ASCII,
//Acronym: T_ACWL               Code: 161,
	ENUM,
//Acronym: T_HWLW               Code: 162,
	ASCII,
//Acronym: T_MTOD               Code: 163,
	ENUM,
//Acronym: T_THDF               Code: 164,
	ASCII,
//Acronym: T_TINT               Code: 165,
	INTE,
//Acronym: T_TSVL               Code: 166,
	ASCII,
//Acronym: T_VAHC               Code: 167,
	ASCII,
//Acronym: TIMEND               Code: 168,
	ASCII,
//Acronym: TIMSTA               Code: 169,
	ASCII,
//Acronym: $TINTS                       Code: 170,
	ENUM,
//Acronym: TOPSHP                       Code: 171,
	ENUM,
//Acronym: TRAFIC                       Code: 172,
	ENUM,
//Acronym: VALACM               Code: 173,
	FLOAT,
//Acronym: VALDCO                       Code: 174,
	FLOAT,
//Acronym: VALLMA               Code: 175,
	FLOAT,
//Acronym: VALMAG               Code: 176,
	FLOAT,
//Acronym: VALMXR                       Code: 177,
	FLOAT,
//Acronym: VALNMR                       Code: 178,
	FLOAT,
//Acronym: VALSOU                       Code: 179,
	FLOAT,
//Acronym: VERACC                       Code: 180,
	FLOAT,
//Acronym: VERCLR                       Code: 181,
	FLOAT,
//Acronym: VERCCL                       Code: 182,
	FLOAT,
//Acronym: VERCOP                       Code: 183,
	FLOAT,
//Acronym: VERCSA                       Code: 184,
	FLOAT,
//Acronym: VERDAT                       Code: 185,
	ENUM,
//Acronym: VERLEN                       Code: 186,
	FLOAT,
//Acronym: WATLEV                       Code: 187,
	ENUM,
	//Acronym: CAT_TS                      Code: 188,
	ENUM,
//Acronym: PUNITS               Code: 189,
	ENUM,
};

/* handmade section */
//Acronym: NINFOM                       
	attrib_type[300] = STRING;
//Acronym: NOBJNM                       
    attrib_type[301] = STRING;
//Acronym: NPLDST                       
    attrib_type[302] = STRING;
//Acronym: $NTXST       
    attrib_type[303] = STRING;
//Acronym: NTXTDS       
    attrib_type[304] = STRING;
//Acronym: HORDAT       
    attrib_type[400] = ENUM;
    attrib_type[401] = FLOAT;
//Acronym: QUAPOS
    attrib_type[402] = ENUM;
