//enum p{ V, R, STG, LIN, CON, SCL};
int LS__ACHARE51(void);
int LS__ACHRES51(void);
int LS__ADMARE01(void);
int LS__CBLARE51(void);
int LS__CBLSUB06(void);
int LS__CHCRDEL1(void);
int LS__CHCRID01(void);
int LS__CTNARE51(void);
int LS__CTYARE51(void);
int LS__DWLDEF01(void);
int LS__DWRTCL05(void);
int LS__DWRTCL06(void);
int LS__DWRTCL07(void);
int LS__DWRTCL08(void);
int LS__DWRUTE51(void);
int LS__ENTRES51(void);
int LS__ERBLNA01(void);
int LS__ERBLNB01(void);
int LS__FERYRT01(void);
int LS__FERYRT02(void);
int LS__FSHFAC02(void);
int LS__FSHRES51(void);
int LS__HODATA01(void);
int LS__LOWACC01(void);
int LS__LOWACC11(void);
int LS__LOWACC21(void);
int LS__LOWACC31(void);
int LS__LOWACC41(void);
int LS__MARSYS51(void);
int LS__NAVARE51(void);
int LS__PIPARE51(void);
int LS__PIPARE61(void);
int LS__PIPSOL05(void);
int LS__PIPSOL06(void);
int LS__PLNRTE03(void);
int LS__PRCARE51(void);
int LS__QUESMRK1(void);
int LS__RCRDEF01(void);
int LS__RCRTCL01(void);
int LS__RCRTCL02(void);
int LS__RCRTCL03(void);
int LS__RCRTCL04(void);
int LS__RECDEF02(void);
int LS__RECTRC09(void);
int LS__RECTRC10(void);
int LS__RECTRC11(void);
int LS__RECTRC12(void);
int LS__RESARE51(void);
int LS__SCLBDY51(void);
int LS__TIDINF51(void);
int LS__UNITFTH1(void);
int LS__UNITMTR1(void);
int PT__AIRARE02(void);
int PT__DIAMOND1(void);
int PT__DQUALA11(void);
int PT__DQUALA21(void);
int PT__DQUALB01(void);
int PT__DQUALC01(void);
int PT__DQUALD01(void);
int PT__DQUALU01(void);
int PT__DRGARE01(void);
int PT__FOULAR01(void);
int PT__FSHFAC03(void);
int PT__FSHFAC04(void);
int PT__FSHHAV02(void);
int PT__ICEARE04(void);
int PT__MARCUL02(void);
int PT__MARSHES1(void);
int PT__NODATA03(void);
int PT__OVERSC01(void);
int PT__PRTSUR01(void);
int PT__QUESMRK1(void);
int PT__RCKLDG01(void);
int PT__SNDWAV01(void);
int PT__TSSJCT02(void);
int PT__VEGATN03(void);
int PT__VEGATN04(void);
int SY__ACHARE02(int orient);
int SY__ACHARE51(int orient);
int SY__ACHBRT07(int orient);
int SY__ACHRES51(int orient);
int SY__ACHRES61(int orient);
int SY__ACHRES71(int orient);
int SY__AIRARE02(int orient);
int SY__AISDEF01(int orient);
int SY__AISONE01(int orient);
int SY__AISSIX01(int orient);
int SY__AISSLP01(int orient);
int SY__AISVES01(int orient);
int SY__ARPATG01(int orient);
int SY__ARPONE01(int orient);
int SY__ARPSIX01(int orient);
int SY__BCNCAR01(int orient);
int SY__BCNCAR02(int orient);
int SY__BCNCAR03(int orient);
int SY__BCNCAR04(int orient);
int SY__BCNDEF13(int orient);
int SY__BCNGEN01(int orient);
int SY__BCNGEN03(int orient);
int SY__BCNISD21(int orient);
int SY__BCNLAT15(int orient);
int SY__BCNLAT16(int orient);
int SY__BCNLAT21(int orient);
int SY__BCNLAT22(int orient);
int SY__BCNLTC01(int orient);
int SY__BCNSAW13(int orient);
int SY__BCNSAW21(int orient);
int SY__BCNSPP13(int orient);
int SY__BCNSPP21(int orient);
int SY__BCNSTK02(int orient);
int SY__BCNTOW01(int orient);
int SY__BLKADJ01(int orient);
int SY__BOYBAR01(int orient);
int SY__BOYCAN01(int orient);
int SY__BOYCAR01(int orient);
int SY__BOYCAR02(int orient);
int SY__BOYCAR03(int orient);
int SY__BOYCAR04(int orient);
int SY__BOYCON01(int orient);
int SY__BOYDEF03(int orient);
int SY__BOYGEN03(int orient);
int SY__BOYINB01(int orient);
int SY__BOYISD12(int orient);
int SY__BOYLAT13(int orient);
int SY__BOYLAT14(int orient);
int SY__BOYLAT23(int orient);
int SY__BOYLAT24(int orient);
int SY__BOYMOR01(int orient);
int SY__BOYMOR03(int orient);
int SY__BOYMOR11(int orient);
int SY__BOYPIL01(int orient);
int SY__BOYSAW12(int orient);
int SY__BOYSPH01(int orient);
int SY__BOYSPP11(int orient);
int SY__BOYSPP15(int orient);
int SY__BOYSPP25(int orient);
int SY__BOYSPR01(int orient);
int SY__BOYSUP01(int orient);
int SY__BOYSUP02(int orient);
int SY__BOYSUP03(int orient);
int SY__BRIDGE01(int orient);
int SY__BRTHNO01(int orient);
int SY__BUAARE02(int orient);
int SY__BUIREL01(int orient);
int SY__BUIREL04(int orient);
int SY__BUIREL05(int orient);
int SY__BUIREL13(int orient);
int SY__BUIREL14(int orient);
int SY__BUIREL15(int orient);
int SY__BUISGL01(int orient);
int SY__BUISGL11(int orient);
int SY__CAIRNS01(int orient);
int SY__CAIRNS11(int orient);
int SY__CBLARE51(int orient);
int SY__CGUSTA02(int orient);
int SY__CHCRDEL1(int orient);
int SY__CHCRID01(int orient);
int SY__CHIMNY01(int orient);
int SY__CHIMNY11(int orient);
int SY__CHINFO06(int orient);
int SY__CHINFO07(int orient);
int SY__CHINFO08(int orient);
int SY__CHINFO09(int orient);
int SY__CHINFO10(int orient);
int SY__CHINFO11(int orient);
int SY__CHKSYM01(int orient);
int SY__CLRLIN01(int orient);
int SY__CRANES01(int orient);
int SY__CTNARE51(int orient);
int SY__CTYARE51(int orient);
int SY__CTYARE71(int orient);
int SY__CURDEF01(int orient);
int SY__CURENT01(int orient);
int SY__CURSRA01(int orient);
int SY__CURSRB01(int orient);
int SY__DANGER01(int orient);
int SY__DANGER02(int orient);
int SY__DANGER03(int orient);
int SY__DAYSQR01(int orient);
int SY__DAYSQR21(int orient);
int SY__DAYTRI01(int orient);
int SY__DAYTRI05(int orient);
int SY__DAYTRI21(int orient);
int SY__DAYTRI25(int orient);
int SY__DIRBOY01(int orient);
int SY__DIRBOYA1(int orient);
int SY__DIRBOYB1(int orient);
int SY__DISMAR03(int orient);
int SY__DISMAR04(int orient);
int SY__DNGHILIT(int orient);
int SY__DOMES001(int orient);
int SY__DOMES011(int orient);
int SY__DSHAER01(int orient);
int SY__DSHAER11(int orient);
int SY__DWRTPT51(int orient);
int SY__DWRUTE51(int orient);
int SY__EBBSTR01(int orient);
int SY__EBLVRM11(int orient);
int SY__ENTRES51(int orient);
int SY__ENTRES61(int orient);
int SY__ENTRES71(int orient);
int SY__ERBLTIK1(int orient);
int SY__EVENTS02(int orient);
int SY__FAIRWY51(int orient);
int SY__FAIRWY52(int orient);
int SY__FLASTK01(int orient);
int SY__FLASTK11(int orient);
int SY__FLDSTR01(int orient);
int SY__FLGSTF01(int orient);
int SY__FOGSIG01(int orient);
int SY__FORSTC01(int orient);
int SY__FORSTC11(int orient);
int SY__FOULGND1(int orient);
int SY__FRYARE51(int orient);
int SY__FRYARE52(int orient);
int SY__FSHFAC02(int orient);
int SY__FSHFAC03(int orient);
int SY__FSHGRD01(int orient);
int SY__FSHHAV01(int orient);
int SY__FSHRES51(int orient);
int SY__FSHRES61(int orient);
int SY__FSHRES71(int orient);
int SY__GATCON03(int orient);
int SY__GATCON04(int orient);
int SY__HILTOP01(int orient);
int SY__HILTOP11(int orient);
int SY__HRBFAC09(int orient);
int SY__HULKES01(int orient);
int SY__INFARE51(int orient);
int SY__INFORM01(int orient);
int SY__ISODGR01(int orient);
int SY__ITZARE51(int orient);
int SY__LIGHTDEF(int orient);
int SY__LIGHTS01(int orient);
int SY__LIGHTS02(int orient);
int SY__LIGHTS03(int orient);
int SY__LIGHTS81(int orient);
int SY__LIGHTS82(int orient);
int SY__LITFLT01(int orient);
int SY__LITFLT02(int orient);
int SY__LITVES01(int orient);
int SY__LITVES02(int orient);
int SY__LNDARE01(int orient);
int SY__LOCMAG01(int orient);
int SY__LOCMAG51(int orient);
int SY__LOWACC01(int orient);
int SY__MAGVAR01(int orient);
int SY__MAGVAR51(int orient);
int SY__MARCUL02(int orient);
int SY__MONUMT02(int orient);
int SY__MONUMT12(int orient);
int SY__MORFAC03(int orient);
int SY__MORFAC04(int orient);
int SY__MSTCON04(int orient);
int SY__MSTCON14(int orient);
int SY__NORTHAR1(int orient);
int SY__NOTBRD11(int orient);
int SY__OBSTRN01(int orient);
int SY__OBSTRN02(int orient);
int SY__OBSTRN03(int orient);
int SY__OBSTRN11(int orient);
int SY__OFSPLF01(int orient);
int SY__OSPONE02(int orient);
int SY__OSPSIX02(int orient);
int SY__OWNSHP01(int orient);
int SY__OWNSHP05(int orient);
int SY__PASTRK01(int orient);
int SY__PASTRK02(int orient);
int SY__PILBOP02(int orient);
int SY__PILPNT02(int orient);
int SY__PLNPOS01(int orient);
int SY__PLNPOS02(int orient);
int SY__POSGEN01(int orient);
int SY__POSGEN03(int orient);
int SY__POSGEN04(int orient);
int SY__POSITN02(int orient);
int SY__PRCARE12(int orient);
int SY__PRCARE51(int orient);
int SY__PRDINS02(int orient);
int SY__PRICKE03(int orient);
int SY__PRICKE04(int orient);
int SY__QUAPOS01(int orient);
int SY__QUARRY01(int orient);
int SY__QUESMRK1(int orient);
int SY__RACNSP01(int orient);
int SY__RADRFL03(int orient);
int SY__RASCAN01(int orient);
int SY__RASCAN11(int orient);
int SY__RCLDEF01(int orient);
int SY__RCTLPT52(int orient);
int SY__RDOCAL02(int orient);
int SY__RDOCAL03(int orient);
int SY__RDOSTA02(int orient);
int SY__RECDEF51(int orient);
int SY__RECTRC55(int orient);
int SY__RECTRC56(int orient);
int SY__RECTRC57(int orient);
int SY__RECTRC58(int orient);
int SY__REFPNT02(int orient);
int SY__RETRFL01(int orient);
int SY__RETRFL02(int orient);
int SY__RFNERY01(int orient);
int SY__RFNERY11(int orient);
int SY__ROLROL01(int orient);
int SY__RSCSTA02(int orient);
int SY__RSRDEF51(int orient);
int SY__RTLDEF51(int orient);
int SY__RTPBCN02(int orient);
int SY__SCALEB10(int orient);
int SY__SCALEB11(int orient);
int SY__SILBUI01(int orient);
int SY__SILBUI11(int orient);
int SY__SISTAT02(int orient);
int SY__SMCFAC02(int orient);
int SY__SNDWAV02(int orient);
int SY__SOUNDG00(int orient);
int SY__SOUNDG01(int orient);
int SY__SOUNDG02(int orient);
int SY__SOUNDG03(int orient);
int SY__SOUNDG04(int orient);
int SY__SOUNDG05(int orient);
int SY__SOUNDG06(int orient);
int SY__SOUNDG07(int orient);
int SY__SOUNDG08(int orient);
int SY__SOUNDG09(int orient);
int SY__SOUNDG10(int orient);
int SY__SOUNDG11(int orient);
int SY__SOUNDG12(int orient);
int SY__SOUNDG13(int orient);
int SY__SOUNDG14(int orient);
int SY__SOUNDG15(int orient);
int SY__SOUNDG16(int orient);
int SY__SOUNDG17(int orient);
int SY__SOUNDG18(int orient);
int SY__SOUNDG19(int orient);
int SY__SOUNDG20(int orient);
int SY__SOUNDG21(int orient);
int SY__SOUNDG22(int orient);
int SY__SOUNDG23(int orient);
int SY__SOUNDG24(int orient);
int SY__SOUNDG25(int orient);
int SY__SOUNDG26(int orient);
int SY__SOUNDG27(int orient);
int SY__SOUNDG28(int orient);
int SY__SOUNDG29(int orient);
int SY__SOUNDG30(int orient);
int SY__SOUNDG31(int orient);
int SY__SOUNDG32(int orient);
int SY__SOUNDG33(int orient);
int SY__SOUNDG34(int orient);
int SY__SOUNDG35(int orient);
int SY__SOUNDG36(int orient);
int SY__SOUNDG37(int orient);
int SY__SOUNDG38(int orient);
int SY__SOUNDG39(int orient);
int SY__SOUNDG40(int orient);
int SY__SOUNDG41(int orient);
int SY__SOUNDG42(int orient);
int SY__SOUNDG43(int orient);
int SY__SOUNDG44(int orient);
int SY__SOUNDG45(int orient);
int SY__SOUNDG46(int orient);
int SY__SOUNDG47(int orient);
int SY__SOUNDG48(int orient);
int SY__SOUNDG49(int orient);
int SY__SOUNDG50(int orient);
int SY__SOUNDG51(int orient);
int SY__SOUNDG52(int orient);
int SY__SOUNDG53(int orient);
int SY__SOUNDG54(int orient);
int SY__SOUNDG55(int orient);
int SY__SOUNDG56(int orient);
int SY__SOUNDG57(int orient);
int SY__SOUNDG58(int orient);
int SY__SOUNDG59(int orient);
int SY__SOUNDGB1(int orient);
int SY__SOUNDGC2(int orient);
int SY__SOUNDS00(int orient);
int SY__SOUNDS01(int orient);
int SY__SOUNDS02(int orient);
int SY__SOUNDS03(int orient);
int SY__SOUNDS04(int orient);
int SY__SOUNDS05(int orient);
int SY__SOUNDS06(int orient);
int SY__SOUNDS07(int orient);
int SY__SOUNDS08(int orient);
int SY__SOUNDS09(int orient);
int SY__SOUNDS10(int orient);
int SY__SOUNDS11(int orient);
int SY__SOUNDS12(int orient);
int SY__SOUNDS13(int orient);
int SY__SOUNDS14(int orient);
int SY__SOUNDS15(int orient);
int SY__SOUNDS16(int orient);
int SY__SOUNDS17(int orient);
int SY__SOUNDS18(int orient);
int SY__SOUNDS19(int orient);
int SY__SOUNDS20(int orient);
int SY__SOUNDS21(int orient);
int SY__SOUNDS22(int orient);
int SY__SOUNDS23(int orient);
int SY__SOUNDS24(int orient);
int SY__SOUNDS25(int orient);
int SY__SOUNDS26(int orient);
int SY__SOUNDS27(int orient);
int SY__SOUNDS28(int orient);
int SY__SOUNDS29(int orient);
int SY__SOUNDS30(int orient);
int SY__SOUNDS31(int orient);
int SY__SOUNDS32(int orient);
int SY__SOUNDS33(int orient);
int SY__SOUNDS34(int orient);
int SY__SOUNDS35(int orient);
int SY__SOUNDS36(int orient);
int SY__SOUNDS37(int orient);
int SY__SOUNDS38(int orient);
int SY__SOUNDS39(int orient);
int SY__SOUNDS40(int orient);
int SY__SOUNDS41(int orient);
int SY__SOUNDS42(int orient);
int SY__SOUNDS43(int orient);
int SY__SOUNDS44(int orient);
int SY__SOUNDS45(int orient);
int SY__SOUNDS46(int orient);
int SY__SOUNDS47(int orient);
int SY__SOUNDS48(int orient);
int SY__SOUNDS49(int orient);
int SY__SOUNDS50(int orient);
int SY__SOUNDS51(int orient);
int SY__SOUNDS52(int orient);
int SY__SOUNDS53(int orient);
int SY__SOUNDS54(int orient);
int SY__SOUNDS55(int orient);
int SY__SOUNDS56(int orient);
int SY__SOUNDS57(int orient);
int SY__SOUNDS58(int orient);
int SY__SOUNDS59(int orient);
int SY__SOUNDSA1(int orient);
int SY__SOUNDSB1(int orient);
int SY__SOUNDSC2(int orient);
int SY__SPRING02(int orient);
int SY__SWPARE51(int orient);
int SY__TIDCUR01(int orient);
int SY__TIDCUR02(int orient);
int SY__TIDCUR03(int orient);
int SY__TIDEHT01(int orient);
int SY__TIDSTR01(int orient);
int SY__TMARDEF1(int orient);
int SY__TMARDEF2(int orient);
int SY__TMBYRD01(int orient);
int SY__TNKCON02(int orient);
int SY__TNKCON12(int orient);
int SY__TNKFRM01(int orient);
int SY__TNKFRM11(int orient);
int SY__TOPMAR02(int orient);
int SY__TOPMAR04(int orient);
int SY__TOPMAR05(int orient);
int SY__TOPMAR06(int orient);
int SY__TOPMAR07(int orient);
int SY__TOPMAR08(int orient);
int SY__TOPMAR10(int orient);
int SY__TOPMAR12(int orient);
int SY__TOPMAR13(int orient);
int SY__TOPMAR14(int orient);
int SY__TOPMAR16(int orient);
int SY__TOPMAR17(int orient);
int SY__TOPMAR18(int orient);
int SY__TOPMAR22(int orient);
int SY__TOPMAR24(int orient);
int SY__TOPMAR25(int orient);
int SY__TOPMAR26(int orient);
int SY__TOPMAR27(int orient);
int SY__TOPMAR28(int orient);
int SY__TOPMAR30(int orient);
int SY__TOPMAR32(int orient);
int SY__TOPMAR33(int orient);
int SY__TOPMAR34(int orient);
int SY__TOPMAR36(int orient);
int SY__TOPMAR65(int orient);
int SY__TOPMAR85(int orient);
int SY__TOPMAR86(int orient);
int SY__TOPMAR87(int orient);
int SY__TOPMAR88(int orient);
int SY__TOPMAR89(int orient);
int SY__TOWERS01(int orient);
int SY__TOWERS02(int orient);
int SY__TOWERS03(int orient);
int SY__TOWERS05(int orient);
int SY__TOWERS12(int orient);
int SY__TOWERS15(int orient);
int SY__TREPNT04(int orient);
int SY__TREPNT05(int orient);
int SY__TSLDEF51(int orient);
int SY__TSSCRS51(int orient);
int SY__TSSLPT51(int orient);
int SY__TSSRON51(int orient);
int SY__TWRDEF51(int orient);
int SY__TWRTPT52(int orient);
int SY__TWRTPT53(int orient);
int SY__UNITFTH1(int orient);
int SY__UNITMTR1(int orient);
int SY__UWTROC03(int orient);
int SY__UWTROC04(int orient);
int SY__VECGND01(int orient);
int SY__VECGND21(int orient);
int SY__VECWTR01(int orient);
int SY__VECWTR21(int orient);
int SY__WATTUR02(int orient);
int SY__WAYPNT01(int orient);
int SY__WAYPNT03(int orient);
int SY__WAYPNT11(int orient);
int SY__WEDKLP03(int orient);
int SY__WIMCON01(int orient);
int SY__WIMCON11(int orient);
int SY__WNDFRM51(int orient);
int SY__WNDFRM61(int orient);
int SY__WNDMIL02(int orient);
int SY__WNDMIL12(int orient);
int SY__WRECKS01(int orient);
int SY__WRECKS04(int orient);
int SY__WRECKS05(int orient);
int SY__PLNSPD03(int orient);
int SY__PLNSPD04(int orient);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__QUAPOS01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__DEPCNT02(void);
int 	CS__DEPARE01(void);
int 	CS__DEPARE01(void);
int 	CS__DEPARE01(void);
int 	CS__DEPARE01(void);
int 	CS__DEPCNT02(void);
int 	CS__DEPCNT02(void);
int 	CS__DEPARE01(void);
int 	CS__DEPARE01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__QUAPOS01(void);
int 	CS__QUAPOS01(void);
int 	CS__QUAPOS01(void);
int 	CS__LIGHTS04(void);
int 	CS__LIGHTS04(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__SLCONS03(void);
int 	CS__SLCONS03(void);
int 	CS__OBSTRN04(void);
int 	CS__OBSTRN04(void);
int 	CS__OBSTRN04(void);
int 	CS__OBSTRN04(void);
int 	CS__OBSTRN04(void);
int 	CS__OBSTRN04(void);
int 	CS__OBSTRN04(void);
int 	CS__OBSTRN04(void);
int 	CS__OBSTRN04(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__RESARE02(void);
int 	CS__RESTRN01(void);
int 	CS__RESARE02(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__SLCONS03(void);
int 	CS__SLCONS03(void);
int 	CS__SLCONS03(void);
int 	CS__SLCONS03(void);
int 	CS__SLCONS03(void);
int 	CS__SOUNDG02(void);
int 	CS__SOUNDG02(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__TOPMAR01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__RESTRN01(void);
int 	CS__OBSTRN04(void);
int 	CS__OBSTRN04(void);
int 	CS__WRECKS02(void);
int 	CS__WRECKS02(void);
int 	CS__WRECKS02(void);
int 	CS__WRECKS02(void);
int 	CS__DATCVR01(void);
int 	CS__DATCVR01(void);
int 	CS__DATCVR01(void);
int 	CS__DATCVR01(void);
